document.addEventListener("DOMContentLoaded", function() {
    const emojiContainer = document.getElementById("emojiContainer");
    const searchInput = document.getElementById("searchInput");
    const searchButton = document.getElementById("searchButton");

    const emojis = [
            { emoji: "😀", emotion: "Happy", description: "A smiling face with big eyes and wide smile" },
            { emoji: "😢", emotion: "Sad", description: "A crying face with a small drop of tear" },
            { emoji: "😎", emotion: "Cool", description: "A face with sunglasses, showing a cool attitude" },
            { emoji: "😴", emotion: "Sleepy", description: "A sleeping face, often used to represent tiredness or sleepiness" },
            { emoji: "🤔", emotion: "Thinking", description: "A face with a raised eyebrow, indicating thinking or questioning" },
            { emoji: "😍", emotion: "Love", description: "A face with heart-shaped eyes, expressing love or admiration" },
            { emoji: "😊", emotion: "Blush", description: "A smiling face with rosy cheeks, expressing happiness or shyness" },
            { emoji: "😋", emotion: "Yum", description: "A face with a tongue out, expressing enjoyment or deliciousness" },
            { emoji: "😇", emotion: "Angel", description: "A face with a halo, representing innocence or goodness" },
            { emoji: "😈", emotion: "Devil", description: "A face with horns, representing mischief or naughtiness" },
            { emoji: "🐶", emotion: "Dog", description: "A cute dog face, often representing loyalty or friendliness" },
            { emoji: "🐱", emotion: "Cat", description: "A playful cat face, often representing independence or curiosity" },
            { emoji: "🌹", emotion: "Rose", description: "A blooming rose, often representing love or beauty" },
            { emoji: "🌈", emotion: "Rainbow", description: "A colorful rainbow, often representing diversity or hope" },
            { emoji: "🎉", emotion: "Party", description: "A party popper, often used to represent celebrations or excitement" },
             { emoji: "😀", emotion: "Happy", description: "A smiling face with big eyes and wide smile" },
                { emoji: "😃", emotion: "Happy", description: "A smiling face with open eyes and a wide smile" },
                { emoji: "😄", emotion: "Happy", description: "A smiling face with open eyes and smiling mouth" },
                { emoji: "😁", emotion: "Happy", description: "A smiling face with open eyes and a broad smile" },
                { emoji: "😆", emotion: "Happy", description: "A smiling face with open eyes and tightly closed mouth" },
                { emoji: "😅", emotion: "Happy", description: "A smiling face with open eyes and a drop of sweat on its forehead" },
                { emoji: "😂", emotion: "Happy", description: "A laughing face with tears of joy" },
                { emoji: "🤣", emotion: "Happy", description: "A rolling on the floor laughing face" },
                { emoji: "😊", emotion: "Happy", description: "A smiling face with smiling eyes" },
                { emoji: "😇", emotion: "Happy", description: "A smiling face with a halo" },
                { emoji: "🙂", emotion: "Happy", description: "A slightly smiling face" },
                { emoji: "🙃", emotion: "Happy", description: "A upside-down face" },
                { emoji: "😉", emotion: "Happy", description: "A winking face" },
                { emoji: "😌", emotion: "Happy", description: "A relieved face" },
                { emoji: "😍", emotion: "Love", description: "A smiling face with heart-shaped eyes" },
                { emoji: "😘", emotion: "Love", description: "A face blowing a kiss" },
                { emoji: "😗", emotion: "Love", description: "A kissing face" },
                { emoji: "😙", emotion: "Love", description: "A kissing face with smiling eyes" },
                { emoji: "😚", emotion: "Love", description: "A kissing face with closed eyes" },
                { emoji: "😋", emotion: "Happy", description: "A face savoring food" },
                { emoji: "😛", emotion: "Happy", description: "A face with tongue out" },
                { emoji: "😜", emotion: "Happy", description: "A winking face with tongue out" },
                { emoji: "🤪", emotion: "Happy", description: "A zany face" },
                { emoji: "😝", emotion: "Happy", description: "A squinting face with tongue out" },
                { emoji: "🤑", emotion: "Happy", description: "A face with money symbols for eyes" },
                { emoji: "🤗", emotion: "Happy", description: "A hugging face" },
                { emoji: "🤓", emotion: "Happy", description: "A face with glasses" },
                { emoji: "😎", emotion: "Cool", description: "A smiling face with sunglasses" },
                { emoji: "🤩", emotion: "Happy", description: "A star-struck face" },
                { emoji: "😏", emotion: "Happy", description: "A smirking face" },
                { emoji: "😒", emotion: "Neutral", description: "A unamused face" },
                { emoji: "😞", emotion: "Sad", description: "A disappointed face" },
                { emoji: "😔", emotion: "Sad", description: "A pensive face" },
                { emoji: "😟", emotion: "Sad", description: "A worried face" },
                { emoji: "😕", emotion: "Sad", description: "A confused face" },
                { emoji: "🙁", emotion: "Sad", description: "A slightly frowning face" },
                { emoji: "☹️", emotion: "Sad", description: "A frowning face" },
                { emoji: "😣", emotion: "Sad", description: "A persevering face" },
                { emoji: "😖", emotion: "Sad", description: "A confounded face" },
                { emoji: "😫", emotion: "Sad", description: "A tired face" },
                { emoji: "😩", emotion: "Sad", description: "A weary face" },
                { emoji: "😤", emotion: "Angry", description: "A face with steam from nose" },
                { emoji: "😠", emotion: "Angry", description: "A angry face" },
                { emoji: "😡", emotion: "Angry", description: "A pouting face" },
                { emoji: "😶", emotion: "Neutral", description: "A face without mouth" },
                { emoji: "😐", emotion: "Neutral", description: "A neutral face" },
                { emoji: "😑", emotion: "Neutral", description: "A expressionless face" },
                { emoji: "😯", emotion: "Surprised", description: "A surprised face" },
                { emoji: "😦", emotion: "Surprised", description: "A frowning face with open mouth" },
                { emoji: "😧", emotion: "Surprised", description: "A anguished face" },
                { emoji: "😮", emotion: "Surprised", description: "A face with open mouth" },
                { emoji: "😲", emotion: "Surprised", description: "A astonished face" },
                { emoji: "😳", emotion: "Embarrassed", description: "A flushed face" },
{ emoji: "🥺", emotion: "Pleading", description: "A pleading face" },
{ emoji: "😦", emotion: "Frowning", description: "A frowning face with open mouth" },
{ emoji: "😧", emotion: "Anguished", description: "A face with open mouth and raised eyebrows" },
{ emoji: "😨", emotion: "Fearful", description: "A fearful face" },
{ emoji: "😰", emotion: "Anxious", description: "A face with open mouth and cold sweat" },
{ emoji: "😥", emotion: "Sad", description: "A disappointed but relieved face" },
{ emoji: "😢", emotion: "Crying", description: "A crying face" },
{ emoji: "😭", emotion: "Loudly Crying", description: "A loudly crying face" },
{ emoji: "😱", emotion: "Screaming", description: "A face screaming in fear" },
{ emoji: "😖", emotion: "Confounded", description: "A confounded face" },
{ emoji: "😣", emotion: "Persevering", description: "A persevering face" },
{ emoji: "😞", emotion: "Disappointed", description: "A disappointed face" },
{ emoji: "😓", emotion: "Sweat", description: "A face with cold sweat" },
{ emoji: "😩", emotion: "Weary", description: "A weary face" },
{ emoji: "😫", emotion: "Tired", description: "A tired face" },
{ emoji: "🥱", emotion: "Yawning", description: "A yawning face" },
{ emoji: "😤", emotion: "Steam From Nose", description: "A face with steam from nose" },
{ emoji: "😡", emotion: "Pouting", description: "A pouting face" },
{ emoji: "😠", emotion: "Angry", description: "An angry face" },
{ emoji: "🤬", emotion: "Cursing", description: "A face with symbols over mouth representing cursing" },
{ emoji: "😈", emotion: "Smiling Face with Horns", description: "A smiling face with horns" },
{ emoji: "👿", emotion: "Angry Face with Horns", description: "An angry face with horns" },
{ emoji: "💀", emotion: "Skull", description: "A skull" },
{ emoji: "☠️", emotion: "Skull and Crossbones", description: "A skull and crossbones" },
{ emoji: "💩", emotion: "Poo", description: "A pile of poo" },
{ emoji: "🤡", emotion: "Clown Face", description: "A clown face" },
{ emoji: "👹", emotion: "Ogre", description: "An ogre" },
{ emoji: "👺", emotion: "Goblin", description: "A goblin" },
{ emoji: "👻", emotion: "Ghost", description: "A ghost" },
{ emoji: "👽", emotion: "Alien", description: "An alien" },
{ emoji: "👾", emotion: "Alien Monster", description: "An alien monster" },
{ emoji: "🤖", emotion: "Robot", description: "A robot" },
{ emoji: "😺", emotion: "Smiling Cat", description: "A smiling cat face" },
{ emoji: "😸", emotion: "Grinning Cat", description: "A grinning cat face" },
{ emoji: "😹", emotion: "Laughing Cat", description: "A laughing cat face" },
{ emoji: "😻", emotion: "Heart Eyes Cat", description: "A cat face with heart-shaped eyes" },
{ emoji: "😼", emotion: "Cat with Wry Smile", description: "A cat face with wry smile" },
{ emoji: "😽", emotion: "Kissing Cat", description: "A kissing cat face" },
{ emoji: "🙀", emotion: "Weary Cat", description: "A weary cat face" },
{ emoji: "😿", emotion: "Crying Cat", description: "A crying cat face" },
{ emoji: "😾", emotion: "Pouting Cat", description: "A pouting cat face" },
{ emoji: "🙈", emotion: "See-No-Evil Monkey", description: "A monkey covering its eyes" },
{ emoji: "🙉", emotion: "Hear-No-Evil Monkey", description: "A monkey covering its ears" },
{ emoji: "🙊", emotion: "Speak-No-Evil Monkey", description: "A monkey covering its mouth" },
{ emoji: "💋", emotion: "Kiss Mark", description: "A kiss mark" },
{ emoji: "💌", emotion: "Love Letter", description: "A love letter"},
{ emoji: "💘", emotion: "Heart with Arrow", description: "A heart with an arrow" },
{ emoji: "💝", emotion: "Heart with Ribbon", description: "A heart with a ribbon" },
{ emoji: "💖", emotion: "Sparkling Heart", description: "A sparkling heart" },
{ emoji: "💗", emotion: "Growing Heart", description: "A growing heart" },
{ emoji: "💓", emotion: "Beating Heart", description: "A beating heart" },
{ emoji: "💞", emotion: "Revolving Hearts", description: "Two hearts revolving around each other" },
{ emoji: "💕", emotion: "Two Hearts", description: "Two hearts" },
{ emoji: "💟", emotion: "Heart Decoration", description: "A heart decoration" },
{ emoji: "❣️", emotion: "Heart Exclamation", description: "A heart exclamation" },
{ emoji: "💔", emotion: "Broken Heart", description: "A broken heart" },
{ emoji: "❤️", emotion: "Red Heart", description: "A red heart" },
{ emoji: "🧡", emotion: "Orange Heart", description: "An orange heart" },
{ emoji: "💛", emotion: "Yellow Heart", description: "A yellow heart" },
{ emoji: "💚", emotion: "Green Heart", description: "A green heart" },
{ emoji: "💙", emotion: "Blue Heart", description: "A blue heart" },
{ emoji: "💜", emotion: "Purple Heart", description: "A purple heart" },
{ emoji: "🤎", emotion: "Brown Heart", description: "A brown heart" },
{ emoji: "🖤", emotion: "Black Heart", description: "A black heart" },
{ emoji: "🤍", emotion: "White Heart", description: "A white heart" },
{ emoji: "💯", emotion: "Hundred Points", description: "Hundred points symbol" },
{ emoji: "💢", emotion: "Anger Symbol", description: "Anger symbol" },
{ emoji: "💥", emotion: "Collision", description: "Collision symbol" },
{ emoji: "💫", emotion: "Dizzy", description: "Dizzy symbol" },
{ emoji: "💦", emotion: "Sweat Droplets", description: "Sweat droplets" },
{ emoji: "💨", emotion: "Dashing Away", description: "Dashing away symbol" },
{ emoji: "🕳️", emotion: "Hole", description: "Hole" },
{ emoji: "💣", emotion: "Bomb", description: "Bomb" },
{ emoji: "💬", emotion: "Speech Balloon", description: "Speech balloon" },
{ emoji: "👁️‍🗨️", emotion: "Eye in Speech Bubble", description: "Eye in speech bubble" },
{ emoji: "🗨️", emotion: "Left Speech Bubble", description: "Left speech bubble" },
{ emoji: "🗯️", emotion: "Right Anger Bubble", description: "Right anger bubble" },
{ emoji: "💭", emotion: "Thought Balloon", description: "Thought balloon" },
{ emoji: "💤", emotion: "Zzz", description: "Zzz" },
{ emoji: "👋", emotion: "Waving Hand", description: "Waving hand" },
{ emoji: "🤚", emotion: "Raised Back of Hand", description: "Raised back of hand" },
{ emoji: "🖐️", emotion: "Hand with Fingers Splayed", description: "Hand with fingers splayed" },
{ emoji: "✋", emotion: "Raised Hand", description: "Raised hand" },
{ emoji: "🖖", emotion: "Vulcan Salute", description: "Vulcan salute" },
{ emoji: "👌", emotion: "OK Hand", description: "OK hand" },
{ emoji: "🤌", emotion: "Pinched Fingers", description: "Pinched fingers" },
{ emoji: "🤏", emotion: "Pinching Hand", description: "Pinching hand" },
{ emoji: "✌️", emotion: "Victory Hand", description: "Victory hand" },
{ emoji: "🤞", emotion: "Crossed Fingers", description: "Crossed fingers" },
{ emoji: "🤟", emotion: "Love-You Gesture", description: "Love-you gesture" },
{ emoji: "🤘", emotion: "Sign of the Horns", description: "Sign of the horns" },
{ emoji: "🤙", emotion: "Call Me Hand", description: "Call me hand" },
{ emoji: "👈", emotion: "Backhand Index Pointing Left", description: "Backhand index pointing left" },
{ emoji: "👉", emotion: "Backhand Index Pointing Right", description: "Backhand index pointing right" },
{ emoji: "👆", emotion: "Backhand Index Pointing Up", description: "Backhand index pointing up" },
{ emoji: "🖕", emotion: "Middle Finger", description: "Middle finger" },
{ emoji: "👇", emotion: "Backhand Index Pointing Down", description: "Backhand index pointing down" },
{ emoji: "☝️", emotion: "Index Pointing Up", description: "Index pointing up" },
{ emoji: "👍", emotion: "Thumbs Up", description: "Thumbs up" },
{ emoji: "👎", emotion: "Thumbs Down", description: "Thumbs down" },
{ emoji: "✊", emotion: "Raised Fist", description: "Raised fist" },
{ emoji: "👊", emotion: "Oncoming Fist", description: "Oncoming fist" },
{ emoji: "🤛", emotion: "Left-Facing Fist", description: "Left-facing fist" },
{ emoji: "🤜", emotion: "Right-Facing Fist", description: "Right-facing fist" },
{ emoji: "👏", emotion: "Clapping Hands", description: "Clapping hands" },
{ emoji: "🙌", emotion: "Raising Hands", description: "Raising hands" },
{ emoji: "🤲", emotion: "Palms Up Together", description: "Palms up together" },
{ emoji: "🤝", emotion: "Handshake", description: "Handshake" },
{ emoji: "🙏", emotion: "Folded Hands", description: "Folded hands" },
{ emoji: "✍️", emotion: "Writing Hand", description: "Writing hand" },
{ emoji: "💅", emotion: "Nail Polish", description: "Nail polish" },
{ emoji: "🤳", emotion: "Selfie", description: "Selfie" },
{ emoji: "💪", emotion: "Flexed Biceps", description: "Flexed biceps" },
{ emoji: "🦾", emotion: "Mechanical Arm", description: "Mechanical arm" },
{ emoji: "🦿", emotion: "Mechanical Leg", description: "Mechanical leg" },
{ emoji: "🦵", emotion: "Leg", description: "Leg" },
{ emoji: "🦶", emotion: "Foot", description: "Foot" },
{ emoji: "👂", emotion: "Ear", description: "Ear" },
{ emoji: "🦻", emotion: "Ear with Hearing Aid", description: "Ear with hearing aid" },
{ emoji: "👃", emotion: "Nose", description: "Nose" },
{ emoji: "🧠", emotion: "Brain", description: "Brain" },
{ emoji: "🫀", emotion: "Anatomical Heart", description: "Anatomical heart" },
{ emoji: "🫁", emotion: "Lungs", description: "Lungs" },
{ emoji: "🦷", emotion: "Tooth", description: "Tooth" },
{ emoji: "🦴", emotion: "Bone", description: "Bone" },
{ emoji: "👀", emotion: "Eyes", description: "Eyes" },
{ emoji: "👁️", emotion: "Eye", description: "Eye" },
{ emoji: "👅", emotion: "Tongue", description: "Tongue" },
{ emoji: "👄", emotion: "Mouth", description: "Mouth" },
{ emoji: "👶", emotion: "Baby", description: "Baby" },
{ emoji: "🧒", emotion: "Child", description: "Child" },
{ emoji: "👦", emotion: "Boy", description: "Boy" },
{ emoji: "👧", emotion: "Girl", description: "Girl" },
{ emoji: "🧑", emotion: "Person", description: "Person" },
{ emoji: "👱‍♀️", emotion: "Woman: Blond Hair", description: "Woman with blond hair" },
{ emoji: "👱", emotion: "Person: Blond Hair", description: "Person with blond hair" },
{ emoji: "🧑‍🦰", emotion: "Person: Red Hair", description: "Person with red hair" },
{ emoji: "👩‍🦰", emotion: "Woman: Red Hair", description: "Woman with red hair" },
{ emoji: "🧑‍🦱", emotion: "Person: Curly Hair", description: "Person with curly hair" },
{ emoji: "👩‍🦱", emotion: "Woman: Curly Hair", description: "Woman with curly hair" },
{ emoji: "🧑‍🦳", emotion: "Person: White Hair", description: "Person with white hair" },
{ emoji: "👩‍🦳", emotion: "Woman: White Hair", description: "Woman with white hair" },
{ emoji: "🧑‍🦲", emotion: "Person: Bald", description: "Person with bald" },
{ emoji: "👩‍🦲", emotion: "Woman: Bald", description: "Woman with bald" },
{ emoji: "👨‍🦲", emotion: "Man: Bald", description: "Man with bald" },
{ emoji: "🧔", emotion: "Bearded Person", description: "Bearded person" },
{ emoji: "👱‍♂️", emotion: "Man: Blond Hair", description: "Man with blond hair" },
{ emoji: "🧔‍♂️", emotion: "Man: Beard", description: "Man with beard" },
{ emoji: "👨‍🦰", emotion: "Man: Red Hair", description: "Man with red hair" },
{ emoji: "👨‍🦱", emotion: "Man: Curly Hair", description: "Man with curly hair" },
{ emoji: "👨‍🦳", emotion: "Man: White Hair", description: "Man with white hair" },
{ emoji: "🧑‍🎓", emotion: "Student", description: "Student" },
{ emoji: "👩‍🎓", emotion: "Woman Student", description: "Woman student" },
{ emoji: "👨‍🎓", emotion: "Man Student", description: "Man student" },
{ emoji: "🧑‍🏫", emotion: "Teacher", description: "Teacher" },
{ emoji: "👩‍🏫", emotion: "Woman Teacher", description: "Woman teacher" },
{ emoji: "👨‍🏫", emotion: "Man Teacher", description: "Man teacher" },
{ emoji: "🧑‍⚖️", emotion: "Judge", description: "Judge" },
{ emoji: "👩‍⚖️", emotion: "Woman Judge", description: "Woman judge" },
{ emoji: "👨‍⚖️", emotion: "Man Judge", description: "Man judge" },
{ emoji: "🧑‍🌾", emotion: "Farmer", description: "Farmer" },
{ emoji: "👩‍🌾", emotion: "Woman Farmer", description: "Woman farmer" },
{ emoji: "👨‍🌾", emotion: "Man Farmer", description: "Man farmer" },
{ emoji: "🧑‍🍳", emotion: "Cook", description: "Cook" },
{ emoji: "👩‍🍳", emotion: "Woman Cook", description: "Woman cook" },
{ emoji: "👨‍🍳", emotion: "Man Cook", description: "Man cook" },
{ emoji: "🧑‍🔧", emotion: "Mechanic", description: "Mechanic" },
{ emoji: "👩‍🔧", emotion: "Woman Mechanic", description: "Woman mechanic" },
{ emoji: "👨‍🔧", emotion: "Man Mechanic", description: "Man mechanic" },
{ emoji: "🧑‍🏭", emotion: "Factory Worker", description: "Factory worker" },
{ emoji: "👩‍🏭", emotion: "Woman Factory Worker", description: "Woman factory worker" },
{ emoji: "👨‍🏭", emotion: "Man Factory Worker", description: "Man factory worker" },
{ emoji: "🧑‍💼", emotion: "Office Worker", description: "Office worker" },
{ emoji: "👩‍💼", emotion: "Woman Office Worker", description: "Woman office worker" },
{ emoji: "👨‍💼", emotion: "Man Office Worker", description: "Man office worker" },
{ emoji: "🧑‍🔬", emotion: "Scientist", description: "Scientist" },
{ emoji: "👩‍🔬", emotion: "Woman Scientist", description: "Woman scientist" },
{ emoji: "👨‍🔬", emotion: "Man Scientist", description: "Man scientist" },
{ emoji: "🧑‍💻", emotion: "Technologist", description: "Technologist" },
{ emoji: "👩‍💻", emotion: "Woman Technologist", description: "Woman technologist" },
{ emoji: "👨‍💻", emotion: "Man Technologist", description: "Man technologist" },
{ emoji: "🧑‍🎤", emotion: "Singer", description: "Singer" },
{ emoji: "👩‍🎤", emotion: "Woman Singer", description: "Woman singer" },
{ emoji: "👨‍🎤", emotion: "Man Singer", description: "Man singer" },
{ emoji: "🧑‍🎨", emotion: "Artist", description: "Artist" },
{ emoji: "👩‍🎨", emotion: "Woman Artist", description: "Woman artist" },
{ emoji: "👨‍🎨", emotion: "Man Artist", description: "Man artist" },
{ emoji: "🧑‍✈️", emotion: "Pilot", description: "Pilot" },
{ emoji: "👩‍✈️", emotion: "Woman Pilot", description: "Woman pilot" },
{ emoji: "👨‍✈️", emotion: "Man Pilot", description: "Man pilot" },
{ emoji: "🧑‍🚀", emotion: "Astronaut", description: "Astronaut" },
{ emoji: "👩‍🚀", emotion: "Woman Astronaut", description: "Woman astronaut" },
{ emoji: "👨‍🚀", emotion: "Man Astronaut", description: "Man astronaut" },
{ emoji: "🧑‍🚒", emotion: "Firefighter", description: "Firefighter" },
{ emoji: "👩‍🚒", emotion: "Woman Firefighter", description: "Woman firefighter" },
{ emoji: "👮", emotion: "Police Officer", description: "Police officer" },
{ emoji: "👮‍♂️", emotion: "Man Police Officer", description: "Man police officer" },
{ emoji: "👮‍♀️", emotion: "Woman Police Officer", description: "Woman police officer" },
{ emoji: "🕵️", emotion: "Detective", description: "Detective" },
{ emoji: "🕵️‍♂️", emotion: "Man Detective", description: "Man detective" },
{ emoji: "🕵️‍♀️", emotion: "Woman Detective", description: "Woman detective" },
{ emoji: "💂", emotion: "Guard", description: "Guard" },
{ emoji: "💂‍♂️", emotion: "Man Guard", description: "Man guard" },
{ emoji: "💂‍♀️", emotion: "Woman Guard", description: "Woman guard" },
{ emoji: "👷", emotion: "Construction Worker", description: "Construction worker" },
{ emoji: "👷‍♂️", emotion: "Man Construction Worker", description: "Man construction worker" },
{ emoji: "👷‍♀️", emotion: "Woman Construction Worker", description: "Woman construction worker" },
{ emoji: "🤴", emotion: "Prince", description: "Prince" },
{ emoji: "👸", emotion: "Princess", description: "Princess" },
{ emoji: "👳", emotion: "Person Wearing Turban", description: "Person wearing turban" },
{ emoji: "👳‍♂️", emotion: "Man Wearing Turban", description: "Man wearing turban" },
{ emoji: "👳‍♀️", emotion: "Woman Wearing Turban", description: "Woman wearing turban" },
{ emoji: "👲", emotion: "Person With Skullcap", description: "Person with skullcap" },
{ emoji: "🧕", emotion: "Woman with Headscarf", description: "Woman with headscarf" },
{ emoji: "🤵", emotion: "Person in Tuxedo", description: "Person in tuxedo" },
{ emoji: "🤵‍♂️", emotion: "Man in Tuxedo", description: "Man in tuxedo" },
{ emoji: "🤵‍♀️", emotion: "Woman in Tuxedo", description: "Woman in tuxedo" },
{ emoji: "👰", emotion: "Person With Veil", description: "Person with veil" },
{ emoji: "👰‍♂️", emotion: "Man with Veil", description: "Man with veil" },
{ emoji: "👰‍♀️", emotion: "Woman with Veil", description: "Woman with veil" },
{ emoji: "🤰", emotion: "Pregnant Woman", description: "Pregnant woman" },
{ emoji: "🤱", emotion: "Breastfeeding", description: "Breastfeeding" },
{ emoji: "👩‍🍼", emotion: "Woman Feeding Baby", description: "Woman feeding baby" },
{ emoji: "👨‍🍼", emotion: "Man Feeding Baby", description: "Man feeding baby" },
{ emoji: "🧑‍🍼", emotion: "Person Feeding Baby", description: "Person feeding baby" },
{ emoji: "🧑‍🎤", emotion: "Singer", description: "Singer" },
{ emoji: "🧑‍🎨", emotion: "Artist", description: "Artist" },
{ emoji: "🧑‍✈️", emotion: "Pilot", description: "Pilot" },
{ emoji: "🧑‍🚀", emotion: "Astronaut", description: "Astronaut" },
{ emoji: "🧑‍🚒", emotion: "Firefighter", description: "Firefighter" },
{ emoji: "👨‍🔬", emotion: "Scientist", description: "Scientist" },
{ emoji: "👩‍🔬", emotion: "Woman Scientist", description: "Woman scientist" },
{ emoji: "👨‍💼", emotion: "Office Worker", description: "Office worker" },
{ emoji: "👩‍💼", emotion: "Woman Office Worker", description: "Woman office worker" },
{ emoji: "👨‍🔧", emotion: "Mechanic", description: "Mechanic" },
{ emoji: "👩‍🔧", emotion: "Woman Mechanic", description: "Woman mechanic" },
{ emoji: "👨‍🏭", emotion: "Factory Worker", description: "Factory worker" },
{ emoji: "👩‍🏭", emotion: "Woman Factory Worker", description: "Woman factory worker" },
{ emoji: "👨‍🌾", emotion: "Farmer", description: "Farmer" },
{ emoji: "👩‍🌾", emotion: "Woman Farmer", description: "Woman farmer" },
{ emoji: "👨‍🍳", emotion: "Cook", description: "Cook" },
{ emoji: "👩‍🍳", emotion: "Woman Cook", description: "Woman cook" },
{ emoji: "👨‍🎓", emotion: "Student", description: "Student" },
{ emoji: "👩‍🎓", emotion: "Woman Student", description: "Woman student" },
{ emoji: "👨‍🎨", emotion: "Artist", description: "Artist" },
{ emoji: "👩‍🎨", emotion: "Woman Artist", description: "Woman artist" },
{ emoji: "👨‍🚒", emotion: "Firefighter", description: "Firefighter" },
{ emoji: "👩‍🚒", emotion: "Woman Firefighter", description: "Woman firefighter" },
{ emoji: "👨‍⚕️", emotion: "Man Health Worker", description: "Man health worker" },
{ emoji: "👩‍⚕️", emotion: "Woman Health Worker", description: "Woman health worker" },
{ emoji: "👨‍🌾", emotion: "Farmer", description: "Farmer" },
{ emoji: "👩‍🌾", emotion: "Woman Farmer", description: "Woman farmer" },
{ emoji: "👨‍🍳", emotion: "Cook", description: "Cook" },
{ emoji: "👨‍🍳", emotion: "Man Cook", description: "Man cook" },
{ emoji: "👩‍🍽️", emotion: "Woman Cook", description: "Woman cook" },
{ emoji: "👨‍🍽️", emotion: "Man Cook", description: "Man cook" },
{ emoji: "👩‍🍽️", emotion: "Woman Cook", description: "Woman cook" },
{ emoji: "👨‍🎤", emotion: "Man Singer", description: "Man singer" },
{ emoji: "👩‍🎤", emotion: "Woman Singer", description: "Woman singer" },
{ emoji: "👨‍🎨", emotion: "Man Artist", description: "Man artist" },
{ emoji: "👩‍🎨", emotion: "Woman Artist", description: "Woman artist" },
{ emoji: "👨‍✈️", emotion: "Man Pilot", description: "Man pilot" },
{ emoji: "👩‍✈️", emotion: "Woman Pilot", description: "Woman pilot" },
{ emoji: "👨‍🚀", emotion: "Man Astronaut", description: "Man astronaut" },
{ emoji: "👩‍🚀", emotion: "Woman Astronaut", description: "Woman astronaut" },
{ emoji: "👨‍🚒", emotion: "Man Firefighter", description: "Man firefighter" },
{ emoji: "👩‍🚒", emotion: "Woman Firefighter", description: "Woman firefighter" },
{ emoji: "👮‍♂️", emotion: "Man Police Officer", description: "Man police officer" },
{ emoji: "👮‍♀️", emotion: "Woman Police Officer", description: "Woman police officer" },
{ emoji: "🕵️‍♂️", emotion: "Man Detective", description: "Man detective" },
{ emoji: "🕵️‍♀️", emotion: "Woman Detective", description: "Woman detective" },
{ emoji: "💂‍♂️", emotion: "Man Guard", description: "Man guard" },
{ emoji: "💂‍♀️", emotion: "Woman Guard", description: "Woman guard" },
{ emoji: "👷‍♂️", emotion: "Man Construction Worker", description: "Man construction worker" },
{ emoji: "👷‍♀️", emotion: "Woman Construction Worker", description: "Woman construction worker" },
{ emoji: "🤴", emotion: "Prince", description: "Prince" },
{ emoji: "👸", emotion: "Princess", description: "Princess" },
{ emoji: "🧝", emotion: "Elf", description: "Elf" },
{ emoji: "🧝‍♂️", emotion: "Man Elf", description: "Man elf" },
{ emoji: "🧝‍♀️", emotion: "Woman Elf", description: "Woman elf" },
{ emoji: "🧙", emotion: "Mage", description: "Mage" },
{ emoji: "🧙‍♂️", emotion: "Man Mage", description: "Man mage" },
{ emoji: "🧙‍♀️", emotion: "Woman Mage", description: "Woman mage" },
{ emoji: "🧚", emotion: "Fairy", description: "Fairy" },
{ emoji: "🧚‍♂️", emotion: "Man Fairy", description: "Man fairy" },
{ emoji: "🧚‍♀️", emotion: "Woman Fairy", description: "Woman fairy" },
{ emoji: "🧛", emotion: "Vampire", description: "Vampire" },
{ emoji: "🧛‍♂️", emotion: "Man Vampire", description: "Man vampire" },
{ emoji: "🧛‍♀️", emotion: "Woman Vampire", description: "Woman vampire" },
{ emoji: "🧜", emotion: "Merperson", description: "Merperson" },
{ emoji: "🧜‍♂️", emotion: "Merman", description: "Merman" },
{ emoji: "🧜‍♀️", emotion: "Mermaid", description: "Mermaid" },
{ emoji: "🧝‍♂️", emotion: "Man Elf", description: "Man elf" },
{ emoji: "🧝‍♀️", emotion: "Woman Elf", description: "Woman elf" },
{ emoji: "🧞", emotion: "Genie", description: "Genie" },
{ emoji: "🧞‍♂️", emotion: "Man Genie", description: "Man genie" },
{ emoji: "🧞‍♀️", emotion: "Woman Genie", description: "Woman genie" },
{ emoji: "🧟", emotion: "Zombie", description: "Zombie" },
{ emoji: "🧟‍♂️", emotion: "Man Zombie", description: "Man zombie" },
{ emoji: "🧟‍♀️", emotion: "Woman Zombie", description: "Woman zombie" },
{ emoji: "💆", emotion: "Person Getting Massage", description: "Person getting massage" },
{ emoji: "💆‍♂️", emotion: "Man Getting Massage", description: "Man getting massage" },
{ emoji: "💆‍♀️", emotion: "Woman Getting Massage", description: "Woman getting massage" },
{ emoji: "💇", emotion: "Person Getting Haircut", description: "Person getting haircut" },
{ emoji: "💇‍♂️", emotion: "Man Getting Haircut", description: "Man getting haircut" },
{ emoji: "💇‍♀️", emotion: "Woman Getting Haircut", description: "Woman getting haircut" },
{ emoji: "🚶", emotion: "Person Walking", description: "Person walking" },
{ emoji: "🚶‍♂️", emotion: "Man Walking", description: "Man walking" },
{ emoji: "🚶‍♀️", emotion: "Woman Walking", description: "Woman walking" },
{ emoji: "🧍", emotion: "Person Standing", description: "Person standing" },
{ emoji: "🧍‍♂️", emotion: "Man Standing", description: "Man standing" },
{ emoji: "🧍‍♀️", emotion: "Woman Standing", description: "Woman standing" },
{ emoji: "🧎", emotion: "Person Kneeling", description: "Person kneeling" },
{ emoji: "🧎‍♂️", emotion: "Man Kneeling", description: "Man kneeling" },
{ emoji: "🧎‍♀️", emotion: "Woman Kneeling", description: "Woman kneeling" },
{ emoji: "🧑‍🦯", emotion: "Person with White Cane", description: "Person with white cane" },
{ emoji: "👨‍🦯", emotion: "Man with White Cane", description: "Man with white cane" },
{ emoji: "👩‍🦯", emotion: "Woman with White Cane", description: "Woman with white cane" },
{ emoji: "🧑‍🦼", emotion: "Person in Motorized Wheelchair", description: "Person in motorized wheelchair" },
{ emoji: "👨‍🦼", emotion: "Man in Motorized Wheelchair", description: "Man in motorized wheelchair" },
{ emoji: "👩‍🦼", emotion: "Woman in Motorized Wheelchair", description: "Woman in motorized wheelchair" },
{ emoji: "🧑‍🦽", emotion: "Person in Manual Wheelchair", description: "Person in manual wheelchair" },
{ emoji: "👨‍🦽", emotion: "Man in Manual Wheelchair", description: "Man in manual wheelchair" },
{ emoji: "👩‍🦽", emotion: "Woman in Manual Wheelchair", description: "Woman in manual wheelchair" },
{ emoji: "🏃", emotion: "Person Running", description: "Person running" },
{ emoji: "🏃‍♂️", emotion: "Man Running", description: "Man running" },
{ emoji: "🏃‍♀️", emotion: "Woman Running", description: "Woman running" },
{ emoji: "💃", emotion: "Woman Dancing", description: "Woman dancing" },
{ emoji: "🕺", emotion: "Man Dancing", description: "Man dancing" },
{ emoji: "🕴️", emotion: "Person in Suit Levitating", description: "Person in suit levitating" },
{ emoji: "👯", emotion: "People with Bunny Ears", description: "People with bunny ears" },
{ emoji: "👯‍♂️", emotion: "Men with Bunny Ears", description: "Men with bunny ears" },
{ emoji: "👯‍♀️", emotion: "Women with Bunny Ears", description: "Women with bunny ears" },
{ emoji: "🧖", emotion: "Person in Steamy Room", description: "Person in steamy room" },
{ emoji: "🧖‍♂️", emotion: "Man in Steamy Room", description: "Man in steamy room" },
{ emoji: "🧖‍♀️", emotion: "Woman in Steamy Room", description: "Woman in steamy room" },
{ emoji: "🧘", emotion: "Person in Lotus Position", description: "Person in lotus position" },
{ emoji: "🧘‍♂️", emotion: "Man in Lotus Position", description: "Man in lotus position" },
{ emoji: "🧘‍♀️", emotion: "Woman in Lotus Position", description: "Woman in lotus position" },
{ emoji: "🧎‍♂️", emotion: "Man Kneeling", description: "Man kneeling" },
{ emoji: "🧎‍♀️", emotion: "Woman Kneeling", description: "Woman kneeling" },
{ emoji: "🏄", emotion: "Person Surfing", description: "Person surfing" },
{ emoji: "🏄‍♂️", emotion: "Man Surfing", description: "Man surfing" },
{ emoji: "🏄‍♀️", emotion: "Woman Surfing", description: "Woman surfing" },
{ emoji: "🏊", emotion: "Person Swimming", description: "Person swimming" },
{ emoji: "🏊‍♂️", emotion: "Man Swimming", description: "Man swimming" },
{ emoji: "🏊‍♀️", emotion: "Woman Swimming", description: "Woman swimming" },
{ emoji: "⛹️", emotion: "Person Bouncing Ball", description: "Person bouncing ball" },
{ emoji: "⛹️‍♂️", emotion: "Man Bouncing Ball", description: "Man bouncing ball" },
{ emoji: "⛹️‍♀️", emotion: "Woman Bouncing Ball", description: "Woman bouncing ball" },
{ emoji: "🏋️", emotion: "Person Lifting Weights", description: "Person lifting weights" },
{ emoji: "🏋️‍♂️", emotion: "Man Lifting Weights", description: "Man lifting weights" },
{ emoji: "🏋️‍♀️", emotion: "Woman Lifting Weights", description: "Woman lifting weights" },
{ emoji: "🚴", emotion: "Person Biking", description: "Person biking" },
{ emoji: "🚴‍♂️", emotion: "Man Biking", description: "Man biking" },
{ emoji: "🚴‍♀️", emotion: "Woman Biking", description: "Woman biking" },
{ emoji: "🚵", emotion: "Person Mountain Biking", description: "Person mountain biking" },
{ emoji: "🚵‍♂️", emotion: "Man Mountain Biking", description: "Man mountain biking" },
{ emoji: "🚵‍♀️", emotion: "Woman Mountain Biking", description: "Woman mountain biking" },
{ emoji: "🤸", emotion: "Person Cartwheeling", description: "Person cartwheeling" },
{ emoji: "🤸‍♂️", emotion: "Man Cartwheeling", description: "Man cartwheeling"},
{ emoji: "🤸‍♀️", emotion: "Woman Cartwheeling", description: "Woman cartwheeling" },
{ emoji: "🤼", emotion: "People Wrestling", description: "People wrestling" },
{ emoji: "🤼‍♂️", emotion: "Men Wrestling", description: "Men wrestling" },
{ emoji: "🤼‍♀️", emotion: "Women Wrestling", description: "Women wrestling" },
{ emoji: "🤽", emotion: "Person Playing Water Polo", description: "Person playing water polo" },
{ emoji: "🤽‍♂️", emotion: "Man Playing Water Polo", description: "Man playing water polo" },
{ emoji: "🤽‍♀️", emotion: "Woman Playing Water Polo", description: "Woman playing water polo" },
{ emoji: "🤾", emotion: "Person Playing Handball", description: "Person playing handball" },
{ emoji: "🤾‍♂️", emotion: "Man Playing Handball", description: "Man playing handball" },
{ emoji: "🤾‍♀️", emotion: "Woman Playing Handball", description: "Woman playing handball" },
{ emoji: "🤹", emotion: "Person Juggling", description: "Person juggling" },
{ emoji: "🤹‍♂️", emotion: "Man Juggling", description: "Man juggling" },
{ emoji: "🤹‍♀️", emotion: "Woman Juggling", description: "Woman juggling" },
{ emoji: "🧘", emotion: "Person in Lotus Position", description: "Person in lotus position" },
{ emoji: "🧘‍♂️", emotion: "Man in Lotus Position", description: "Man in lotus position" },
{ emoji: "🧘‍♀️", emotion: "Woman in Lotus Position", description: "Woman in lotus position" },
{ emoji: "🛀", emotion: "Person Taking Bath", description: "Person taking bath" },
{ emoji: "🛌", emotion: "Person in Bed", description: "Person in bed" },
{ emoji: "🕴️‍♂️", emotion: "Man in Suit Levitating", description: "Man in suit levitating" },
{ emoji: "🕴️‍♀️", emotion: "Woman in Suit Levitating", description: "Woman in suit levitating" },
{ emoji: "🧗", emotion: "Person Climbing", description: "Person climbing" },
{ emoji: "🧗‍♂️", emotion: "Man Climbing", description: "Man climbing" },
{ emoji: "🧗‍♀️", emotion: "Woman Climbing", description: "Woman climbing" },
{ emoji: "🚣", emotion: "Person Rowing Boat", description: "Person rowing boat" },
{ emoji: "🚣‍♂️", emotion: "Man Rowing Boat", description: "Man rowing boat" },
{ emoji: "🚣‍♀️", emotion: "Woman Rowing Boat", description: "Woman rowing boat" },
{ emoji: "🏇", emotion: "Horse Racing", description: "Horse racing" },
{ emoji: "🧑‍🤝‍🧑", emotion: "People Holding Hands", description: "People holding hands" },
{ emoji: "👫", emotion: "Man and Woman Holding Hands", description: "Man and woman holding hands" },
{ emoji: "👬", emotion: "Two Men Holding Hands", description: "Two men holding hands" },
{ emoji: "👭", emotion: "Two Women Holding Hands", description: "Two women holding hands" },
{ emoji: "💑", emotion: "Couple with Heart", description: "Couple with heart" },
{ emoji: "👩‍❤️‍👨", emotion: "Couple with Heart: Woman, Man", description: "Couple with heart: woman, man" },
{ emoji: "👩‍❤️‍👩", emotion: "Couple with Heart: Woman, Woman", description: "Couple with heart: woman, woman" },
{ emoji: "👨‍❤️‍👨", emotion: "Couple with Heart: Man, Man", description: "Couple with heart: man, man" },
{ emoji: "💏", emotion: "Kiss", description: "Kiss" },
{ emoji: "👩‍❤️‍💋‍👨", emotion: "Kiss: Woman, Man", description: "Kiss: woman, man" },
{ emoji: "👩‍❤️‍💋‍👩", emotion: "Kiss: Woman, Woman", description: "Kiss: woman, woman" },
{ emoji: "👨‍❤️‍💋‍👨", emotion: "Kiss: Man, Man", description: "Kiss: man, man" },
{ emoji: "👪", emotion: "Family", description: "Family" },
{ emoji: "👨‍👩‍👦", emotion: "Family: Man, Woman, Boy", description: "Family: man, woman, boy" },
{ emoji: "👨‍👩‍👧", emotion: "Family: Man, Woman, Girl", description: "Family: man, woman, girl" },
{ emoji: "👨‍👩‍👧‍👦", emotion: "Family: Man, Woman, Girl, Boy", description: "Family: man, woman, girl, boy" },
{ emoji: "👨‍👩‍👦‍👦", emotion: "Family: Man, Woman, Boy, Boy", description: "Family: man, woman, boy, boy" },
{ emoji: "👨‍👩‍👧‍👧", emotion: "Family: Man, Woman, Girl, Girl", description: "Family: man, woman, girl, girl" },
{ emoji: "👨‍👦", emotion: "Family: Man, Boy", description: "Family: man, boy" },
{ emoji: "👨‍👦‍👦", emotion: "Family: Man, Boy, Boy", description: "Family: man, boy, boy" },
{ emoji: "👨‍👧", emotion: "Family: Man, Girl", description: "Family: man, girl" },
{ emoji: "👨‍👧‍👦", emotion: "Family: Man, Girl, Boy", description: "Family: man, girl, boy" },
{ emoji: "👨‍👧‍👧", emotion: "Family: Man, Girl, Girl", description: "Family: man, girl, girl" },
{ emoji: "👩‍👦", emotion: "Family: Woman, Boy", description: "Family: woman, boy" },
{ emoji: "👩‍👦‍👦", emotion: "Family: Woman, Boy, Boy", description: "Family: woman, boy, boy" },
{ emoji: "👩‍👧", emotion: "Family: Woman, Girl", description: "Family: woman, girl" },
{ emoji: "👩‍👧‍👦", emotion: "Family: Woman, Girl, Boy", description: "Family: woman, girl, boy" },
{ emoji: "👩‍👧‍👧", emotion: "Family: Woman, Girl, Girl", description: "Family: woman, girl, girl" },
{ emoji: "🗣️", emotion: "Speaking Head", description: "Speaking head" },
{ emoji: "👤", emotion: "Bust in Silhouette", description: "Bust in silhouette" },
{ emoji: "👥", emotion: "Busts in Silhouette", description: "Busts in silhouette" },
{ emoji: "🫂", emotion: "People Hugging", description: "People hugging" },
{ emoji: "💔", emotion: "Broken Heart", description: "Broken heart" },
{ emoji: "❤️", emotion: "Red Heart", description: "Red heart" },
{ emoji: "🧡", emotion: "Orange Heart", description: "Orange heart" },
{ emoji: "💛", emotion: "Yellow Heart", description: "Yellow heart" },
{ emoji: "💚", emotion: "Green Heart", description: "Green heart" },
{ emoji: "💙", emotion: "Blue Heart", description: "Blue heart" },
{ emoji: "💜", emotion: "Purple Heart", description: "Purple heart" },
{ emoji: "🖤", emotion: "Black Heart", description: "Black heart" },
{ emoji: "🤍", emotion: "White Heart", description: "White heart" },
{ emoji: "💖", emotion: "Sparkling Heart", description: "Sparkling heart" },
{ emoji: "💗", emotion: "Growing Heart", description: "Growing heart" },
{ emoji: "💓", emotion: "Beating Heart", description: "Beating heart" },
{ emoji: "💞", emotion: "Revolving Hearts", description: "Revolving hearts" },
{ emoji: "💕", emotion: "Two Hearts", description: "Two hearts" },
{ emoji: "💘", emotion: "Heart with Arrow", description: "Heart with arrow" },
{ emoji: "❣️", emotion: "Heart Exclamation", description: "Heart exclamation" },
{ emoji: "💝", emotion: "Heart with Ribbon", description: "Heart with ribbon" },
{ emoji: "💌", emotion: "Love Letter", description: "Love letter" },
{ emoji: "💐", emotion: "Bouquet", description: "Bouquet" },
{ emoji: "🌸", emotion: "Cherry Blossom", description: "Cherry blossom" },
{ emoji: "💮", emotion: "White Flower", description: "White flower" },
{ emoji: "🏵️", emotion: "Rosette", description: "Rosette" },
{ emoji: "🌹", emotion: "Rose", description: "Rose" },
{ emoji: "🥀", emotion: "Wilted Flower", description: "Wilted flower" },
{ emoji: "🌺", emotion: "Hibiscus", description: "Hibiscus" },
{ emoji: "🌻", emotion: "Sunflower", description: "Sunflower"},
    
    ];

    function displayEmojis(emojis) {
        emojiContainer.innerHTML = "";
        emojis.forEach(emoji => {
            const emojiElement = document.createElement("div");
            emojiElement.classList.add("emoji");
            emojiElement.textContent = emoji.emoji;
            emojiContainer.appendChild(emojiElement);

            const emotionElement = document.createElement("div");
            emotionElement.classList.add("description");
            emotionElement.textContent = emoji.emotion;
            emojiContainer.appendChild(emotionElement);

            const descriptionElement = document.createElement("div");
            descriptionElement.classList.add("description");
            descriptionElement.textContent = emoji.description;
            emojiContainer.appendChild(descriptionElement);
        });
    }

    // Initial display of emojis
    displayEmojis(emojis);

    // Event listener for search input
    searchInput.addEventListener("input", function() {
        const searchTerm = searchInput.value.toLowerCase();
        
        // Filter emojis based on the search term
        const filteredEmojis = emojis.filter(emoji =>
            emoji.emoji.toLowerCase().includes(searchTerm) ||
            emoji.emotion.toLowerCase().includes(searchTerm) ||
            emoji.description.toLowerCase().includes(searchTerm)
        );
        
        // Sort filtered emojis by description matching first
        filteredEmojis.sort((a, b) => {
            const aIndex = a.description.toLowerCase().indexOf(searchTerm);
            const bIndex = b.description.toLowerCase().indexOf(searchTerm);
            return aIndex - bIndex;
        });

        // Display filtered emojis
        displayEmojis(filteredEmojis);
    });
});
